spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id : flower-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/flowers/**
        - id: stock-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/stocks/**
        - id: shop-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/shops/**
        - id: user-microservice
          uri: http://localhost:8084
          predicates:
            - Path=/api/auth/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8222
eureka:
  client:
    register-with-eureka: false
